name: Docker

on:
  push:
    branches: master
  release:
    types: published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push images
        run: |
          docker buildx build \
            --tag ghcr.io/${{ github.repository }}:${{ github.ref }} \
            --tag ghcr.io/${{ github.repository }}:latest \
            --platform linux/amd64,linux/arm64 \
            --push \
            .
